version: "3.8"

services:
  postgres:
    image: postgres:15  # Use the latest stable PostgreSQL version
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pg_network  # Connect to a custom network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - pg_network  # Connect to the same network

volumes:
  postgres_data:
    driver: local

networks:
  pg_network:
    driver: bridge  # Create a user-defined bridge network
