// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github/mauljurassicia/nutrifeat/model"

// AdvancedTableExample demonstrates how to use the AdvancedTable component
func AdvancedTableExample() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = AdvancedTable(TableProps{
			Header: []string{"Name", "Age", "Role", "Status"},
			Rows: []model.TableData{
				{
					"Name":   "John Doe",
					"Age":    "32",
					"Role":   "Nutritionist",
					"Status": "Active",
				},
				{
					"Name":   "Jane Smith",
					"Age":    "28",
					"Role":   "Patient",
					"Status": "Inactive",
				},
				{
					"Name":   "Bob Johnson",
					"Age":    "45",
					"Role":   "Doctor",
					"Status": "Active",
				},
				{
					"Name":   "Alice Williams",
					"Age":    "35",
					"Role":   "Nurse",
					"Status": "Active",
				},
				{
					"Name":   "Charlie Brown",
					"Age":    "52",
					"Role":   "Patient",
					"Status": "Active",
				},
			},
			CurrentPage:  1,
			TotalPages:   2,
			PageSize:     5,
			TotalItems:   10,
			SortColumn:   "Name",
			SortOrder:    "asc",
			OnPageChange: "/api/table-data",
			OnSort:       "/api/table-data",
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
