// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/axzilla/templui/icons"

import i "github.com/callsamu/templicons"

func Topbar() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<header class=\"flex items-center justify-between border-b-2 border-accent-foreground px-6 py-2\"><div class=\"\"><a class=\"font-bold text-xl flex items-center\" href=\"/\" preload=\"mouseover\" hx-boost=\"true\"><span class=\"bg-foreground p-1 rounded mr-2\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = i.Icon("ion:nutrition", i.Params().SetDimensions(32, 32).SetColor("#fff")).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</span> Nutrifeat</a></div><div class=\"flex items-center gap-10\"><div class=\"relative ml-10 hidden sm:block text-muted-foreground\"><!-- Search Icon -->")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = icons.Search(icons.IconProps{Class: "absolute top-1/2 -translate-1/2 left-4"}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<input type=\"text\" placeholder=\"Search your food...\" class=\"pl-10 pr-4 py-2 w-[300px] rounded-full  bg-muted border border-muted-foreground outline-0 focus:border-2 focus:border-accent-foreground\"></div><nav class=\"hidden md:flex items-center gap-4\"><a href=\"#\" class=\"text-sm text-gray-600 hover:text-gray-900\">Help</a> <a href=\"#\" class=\"text-sm text-gray-600 hover:text-gray-900\">Upgrade</a> <a href=\"#\" class=\"text-sm text-gray-600 hover:text-gray-900\">FAQs</a></nav></div><div class=\"flex justify-end\"><div class=\"flex items-center gap-3\"><button class=\"p-2 text-gray-600 hover:text-gray-900 hover:bg-gray-100 rounded-full\"><!-- Bell Icon --><svg class=\"w-5 h-5\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" viewBox=\"0 0 24 24\"><path d=\"M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 00-4 0v.341C8.67 6.165 8 7.388 8 9v5.159c0 .538-.214 1.055-.595 1.436L6 17h9z\"></path></svg></button> <button class=\"p-2 text-gray-600 hover:text-gray-900 hover:bg-gray-100 rounded-full\"><!-- Message Icon --><svg class=\"w-5 h-5\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" viewBox=\"0 0 24 24\"><path d=\"M21 15a2 2 0 01-2 2H7l-4 4V5a2 2 0 012-2h14a2 2 0 012 2z\"></path></svg></button><div class=\"flex items-center gap-2\"><img src=\"https://github.com/shadcn.png\" alt=\"User\" class=\"h-8 w-8 rounded-full\"> <span class=\"text-sm font-medium hidden md:inline\">Ruman</span> <svg width=\"10\" height=\"6\" viewBox=\"0 0 10 6\" class=\"text-gray-500\"><path d=\"M9.99902 1L4.99951 6L-0.000976562 1\" stroke=\"currentColor\" stroke-width=\"1.5\" fill=\"none\"></path></svg></div></div></div></header>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
